### ISSUE TITLE
Preferences schema has wrong encoding

### ISSUE THREAD

**Issue by reyis4402** [krlvm/PowerTunnel-Android#101]
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at io.github.krlvm.powertunnel.android.fragments.PluginSettingsFragment.onCreatePreferences(PluginSettingsFragment.java:67)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
	at android.app.Activity.performStart(Activity.java:7847)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

**Comment by krlvm** [comment]
Which plugin you are trying to configure?

**Comment by reyis4402** [comment]
All plugin settings fail. Plugin settings are not opening.

**Comment by reyis4402** [comment]
DivestOS Android 11 - Mi 9T Davinci

**Comment by krlvm** [comment]
Can you share the full log by enabling Log Viewer in app's settings?
You can use [version 1.9.1](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.9.1) until the issue is resolved.

**Comment by reyis4402** [comment]
`
[powertunnel.log.txt](https://github.com/krlvm/PowerTunnel-Android/files/7857818/powertunnel.log.txt)
`

**Comment by reyis4402** [comment]
[powertunnel.log.txt](https://github.com/krlvm/PowerTunnel-Android/files/7857830/powertunnel.log.txt)

**Comment by krlvm** [comment]
Thank you, I've identified the issue, it is related to the encoding.
![image](https://user-images.githubusercontent.com/51774833/149223962-15997626-b1fc-48da-9635-57048f8478a7.png)

Related: https://github.com/krlvm/PowerTunnel/issues/81

**Comment by krlvm** [comment]
Fix is available in [version 2.0.1](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v2.0.1)
