### ISSUE TITLE
crash (bruh 🗿🗿🗿🗿)

### ISSUE THREAD

**Issue by NSTAdventure** [krlvm/PowerTunnel-Android#106]
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.github.krlvm.powertunnel.android.adapters.AppAdapter.filtrate(io.github.krlvm.powertunnel.android.types.AppInfo$FilterCallback)' on a null object reference
	at io.github.krlvm.powertunnel.android.activities.AppListActivity.setFilter(AppListActivity.java:128)
	at io.github.krlvm.powertunnel.android.activities.AppListActivity.access$000(AppListActivity.java:40)
	at io.github.krlvm.powertunnel.android.activities.AppListActivity$1.onQueryTextSubmit(AppListActivity.java:83)
	at androidx.appcompat.widget.SearchView.onSubmitQuery(SearchView.java:1191)
	at androidx.appcompat.widget.SearchView$7.onEditorAction(SearchView.java:1168)
	at android.widget.TextView.onEditorAction(TextView.java:7079)
	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:357)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7853)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
    

what happened?
(PowerTunnel v 2.0.1)

**Comment by krlvm** [comment]
It was a minor bug, fixed in the upcoming release.

**Comment by NSTAdventure** [comment]
> It was a minor bug, fixed in the upcoming release.

thanks 🙏😊

also don't forgey moyai emojis 🗿🗿🗿🗿
(bruh 🗿🗿🗿🗿🗿)
