### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Scripterr** [krlvm/PowerTunnel-Android#109]
java.lang.IllegalStateException: LittleProxy Server has not been started
	at io.github.krlvm.powertunnel.LittleProxyServer.ensureServerAvailable(LittleProxyServer.java:153)
	at io.github.krlvm.powertunnel.LittleProxyServer.getAddress(LittleProxyServer.java:178)
	at io.github.krlvm.powertunnel.android.managers.ProxyManager.getAddress(ProxyManager.java:210)
	at io.github.krlvm.powertunnel.android.services.TunnelingVpnService.connect(TunnelingVpnService.java:176)
	at io.github.krlvm.powertunnel.android.services.TunnelingVpnService.lambda$onStartCommand$0$io-github-krlvm-powertunnel-android-services-TunnelingVpnService(TunnelingVpnService.java:104)
	at io.github.krlvm.powertunnel.android.services.TunnelingVpnService$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at io.github.krlvm.powertunnel.android.managers.ProxyManager.lambda$start$0$io-github-krlvm-powertunnel-android-managers-ProxyManager(ProxyManager.java:118)
	at io.github.krlvm.powertunnel.android.managers.ProxyManager$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:929)
    

![Screenshot_20220128_093605](https://user-images.githubusercontent.com/42364681/151485602-00e5ab8f-d764-499f-9e8c-6484d85486a5.jpg)

**Comment by krlvm** [comment]
Thanks for reporting, was you able to connect after app restart?

**Comment by Scripterr** [comment]
> Thanks for reporting, was you able to connect after app restart?

Yes, it's working fine right now.
