### ISSUE TITLE
Power Tunnel 2.6 крешится при старте (java.lang.NoSuchMethodError)

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#127]
Power Tunnel 2.6 крешится при старте :

```

java.lang.NoSuchMethodError: No interface method stream()Ljava/util/stream/Stream; in class Ljava/util/Set; or its super classes (declaration of 'java.util.Set' appears in /system/framework/core-libart.jar)
	at io.github.krlvm.powertunnel.plugins.libertytunnel.LibertyTunnel.onProxyInitialization(LibertyTunnel.java:68)
	at io.github.krlvm.powertunnel.PowerTunnel.callPluginsProxyInitializationCallback(PowerTunnel.java:313)
	at io.github.krlvm.powertunnel.PowerTunnel.start(PowerTunnel.java:114)
	at io.github.krlvm.powertunnel.android.managers.ProxyManager.lambda$start$0$io-github-krlvm-powertunnel-android-managers-ProxyManager(ProxyManager.java:126)
	at io.github.krlvm.powertunnel.android.managers.ProxyManager$$ExternalSyntheticLambda0.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)

```

![2022 08 03_01 01 45~01](https://user-images.githubusercontent.com/12525093/182408179-6a948f5a-ace6-435b-8047-9ccd8f1bb654.jpg)

Приложение обнулял (pm clear) - не помогло. Ранее был установлен релиз 2.4

**Comment by krlvm** [comment]
Проблема связана с использованием streams из Java 8, которые поддерживаются в Android нативно только с Android 8 Oreo, но для более старых версий в APK содержится полифил (`coreLibraryDesugaringEnabled`). В коде Android-версии PowerTunnel я ничего связанное с этим не менял, а LibertyTunnel стабильно весит по 11 КБ еще с прошлого года, тем более, что версия 1.0.5, поставляемая в 2.4 тоже использует Streams API. Попробуйте установить ее вручную: https://github.com/krlvm/LibertyTunnel/releases/tag/v1.0.5

**Comment by Baltazar500** [comment]
По поводу версии я ошибся. Была не 2.4, а чуть более раняя. Сейчас точно не скажу какая.

>В коде Android-версии PowerTunnel я ничего связанное с этим не менял, а LibertyTunnel стабильно весит по 11 КБ еще с прошлого года, тем более, что версия 1.0.5, поставляемая в 2.4 тоже использует Streams API. Попробуйте установить ее вручную: https://github.com/krlvm/LibertyTunnel/releases/tag/v1.0.5

Старый плагин снёс, старый накатил. Та же петрушка

```

java.lang.NoSuchMethodError: No interface method stream()Ljava/util/stream/Stream; in class Ljava/util/Set; or its super classes (declaration of 'java.util.Set' appears in /system/framework/core-libart.jar)
	at io.github.krlvm.powertunnel.plugins.libertytunnel.LibertyTunnel.onProxyInitialization(LibertyTunnel.java:69)
	at io.github.krlvm.powertunnel.PowerTunnel.callPluginsProxyInitializationCallback(PowerTunnel.java:313)
	at io.github.krlvm.powertunnel.PowerTunnel.start(PowerTunnel.java:114)
	at io.github.krlvm.powertunnel.android.managers.ProxyManager.lambda$start$0$io-github-krlvm-powertunnel-android-managers-ProxyManager(ProxyManager.java:126)
	at io.github.krlvm.powertunnel.android.managers.ProxyManager$$ExternalSyntheticLambda0.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)

```

**Comment by krlvm** [comment]
Вероятно, проблема в [этом](https://github.com/krlvm/LibertyTunnel/commit/1a3ecd2689629d8823ae6fc04ce704638282eac4) коммите.
Попробуйте: https://github.com/krlvm/LibertyTunnel/releases/tag/v1.0.8

**Comment by Baltazar500** [comment]
>Попробуйте: https://github.com/krlvm/LibertyTunnel/releases/tag/v1.0.8

Запустился без креша :)

**Comment by krlvm** [comment]
Выпустил версию [2.6.1](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v2.6.1) с исправлением

**Comment by NesterovQA** [comment]
а можно ли такое же исправление для android tv ?версия 2.6.3 падает
