### ISSUE TITLE
App crashed when i add my own Plugin

### ISSUE THREAD

**Issue by GuckTubeYT** [krlvm/PowerTunnel-Android#141]
Hello, please help me, why i add my own plugin to my android phone, and i start, the app force close
i build my own plugin using windows (and the architecture is different)
please help me

**Comment by GuckTubeYT** [comment]
> I still have not released the plugin converter, which uses D8 to translate Java bytecode to bytecode compatible with Android Runtime and build classes.dex file.
> 
> I created a very dirty prototype two years ago with which I convert my own plugins, you can use it by executing
> 
> ```
> $ androidify filename.jar filename-Android.jar
> ```
> 
> I have plans to create a Gradle plugin which will do that in clean & automatic way, but I haven't found time to do it yet.
> 
> [androidify.zip](https://github.com/krlvm/PowerTunnel-Android/files/10722467/androidify.zip)

when i run `androidify filename.jar filename-Android.jar` command, i didnt get output file, and i got message like this
`5 was unexpected at this time.`

**Comment by GuckTubeYT** [comment]
and then, i get error message box like this

![image](https://user-images.githubusercontent.com/56192597/218487096-ed21721e-c07b-4c2e-be32-7458af2bd8b0.png)

**Comment by GuckTubeYT** [comment]
is it problem in my JDK or not? my JDK version is = 19 (newest)

**Comment by krlvm** [comment]
You should target JRE 1.8 in your plugin

Also keep in mind that new features from Java 8+ won't work on Android < 8

**Comment by GuckTubeYT** [comment]
> You should target JRE 1.8 in your plugin
> 
> Also keep in mind that new features from Java 8+ won't work on Android < 8

how do i set target jre 1.8?

**Comment by GuckTubeYT** [comment]
> This is a trivial thing: https://github.com/krlvm/PowerTunnel/blob/7dff06e74ea65befe618adc845c8a4cfb3d9985a/build.gradle#L31

oh okay okay, and then, should i use jdk 8 or older?

**Comment by krlvm** [comment]
You just need to add these lines to your build.gradle or decrease SDK level in IntelliJ if you use its build system

**Comment by GuckTubeYT** [comment]
i want to try build the plugin using android phone, but i get this error

![Screenshot_2023-02-14-00-31-33-44_568ed85dd9b4e5f606052ed6d65243e4](https://user-images.githubusercontent.com/56192597/218530057-a52097e3-2fc7-4611-ae1c-a086eaca9d1d.jpg)

do you know how to fix

sorry if i bothering you
and thanks for the fast respond

**Comment by krlvm** [comment]
Weird, it can't resolve `gitRepositories` method I used to add the upstream PowerTunnel repository as library.

Could be a problem related to the environment you are trying to build on, are you sure the Gradle version >= 6.8?
If it still fails, I'd suggest to build on Windows/Linux, I've downloaded the Hosts plugin sources and built it within a minute without problems.

**Comment by GuckTubeYT** [comment]
oh, my gradle version is 4.4.1

**Comment by krlvm** [comment]
Do you have git installed?
I think it would be easier to build on PC.

**Comment by GuckTubeYT** [comment]
> Do you have git installed? I think it would be easier to build on PC.

already

**Comment by GuckTubeYT** [comment]
but i got that error idk why

**Comment by GuckTubeYT** [comment]
![Screenshot_2023-02-14-06-36-55-41_568ed85dd9b4e5f606052ed6d65243e4](https://user-images.githubusercontent.com/56192597/218598750-ceca3e71-eb0b-4e36-b83a-398f04442e36.jpg)
finally, it worked!

**Comment by GuckTubeYT** [comment]
still doesnt work, even i set target jre 1.8
![Screenshot_2023-02-14-07-04-59-61_568ed85dd9b4e5f606052ed6d65243e4](https://user-images.githubusercontent.com/56192597/218602509-b4ebca71-9aae-4adc-a835-4a687882d196.jpg)

**Comment by krlvm** [comment]
You forgot to convert it to Android format

**Comment by GuckTubeYT** [comment]
> You forgot to convert it to Android format

oohhhh, so, i need convert all class to classes.dex?

**Comment by krlvm** [comment]
Yes, you just need to call D8 like `androidify.cmd` does in the my previous reply -https://github.com/krlvm/PowerTunnel-Android/issues/141#issuecomment-1427921374 - the shell script I attached requires Windows, but techicially you can rewrite its commands to execute in your environment.

**Comment by GuckTubeYT** [comment]
> script I attached requires Windows, but techicially you can rewrite its commands to execute

Oh okay okay, thanks

**Comment by GuckTubeYT** [comment]
finally, its worked! thanks

**Comment by pramit-j2-sl** [comment]
What is the build command used build the initial jar file?

When I tried to build the Dex, it gave the following errors:
```
ompiling PowerTunnel-Hosts-1.1.jar to DEX format (API 16)...
Warning in PowerTunnel-Hosts-1.1.jar:io/github/krlvm/powertunnel/plugins/hosts/HostsPlugin.class:
Type `io.github.krlvm.powertunnel.sdk.plugin.PowerTunnelPlugin` was not found, it is required for default or static interface methods desugaring of `io.github.krlvm.powertunnel.plugins.hosts.HostsPlugin`
Warning in PowerTunnel-Hosts-1.1.jar:io/github/krlvm/powertunnel/plugins/hosts/DNSListener.class:
Type `io.github.krlvm.powertunnel.sdk.proxy.ProxyAdapter` was not found, it is required for default or static interface methods desugaring of `io.github.krlvm.powertunnel.plugins.hosts.DNSListener`
Error: DEX file generation failed!
```

It seems, while building the jar, it only took the plugin files, not the dependency files. I am trying to build https://github.com/krlvm/PowerTunnel-Hosts (master). Using the same [`build.gradle`](https://github.com/krlvm/PowerTunnel-Hosts/blob/master/build.gradle) file in that project, where dependencies are mentioned as implementation.

@krlvm @GuckTubeYT

**Comment by krlvm** [comment]
These are warnings - I just tried and got the same warnings, but everything still compiled successfully, most likely you have real errors above in the log.

**Comment by pramit-j2-sl** [comment]
Thanks @krlvm . The script below I used to build the Android byte code loaded jar file. It worked for the Hosts plugin, now testing with the template plugin.

```
#!/bin/bash

# Configuration
INPUT_JAR="PowerTunnel-Hosts-1.1.jar"
OUTPUT_JAR="PowerTunnel-Hosts-1.1-Androidified.jar"
ANDROID_SDK_PATH="/data/Android/Sdk"
BUILD_TOOLS_VERSION="35.0.1"
MIN_API=16
JAVA_PATH="/usr/local/android-studio/jbr"

DEFAULT_XMX="-Xmx1024M"
DEFAULT_XSS="-Xss1m"

# Path setup
D8_PATH="$ANDROID_SDK_PATH/build-tools/$BUILD_TOOLS_VERSION/d8"
ANDROID_JAR="$ANDROID_SDK_PATH/platforms/android-$MIN_API/android.jar"

# Internal Filenames
TEMPDIR="./tmp"

# Validate environment
if [ ! -f "$INPUT_JAR" ]; then
    echo "Error: Input file $INPUT_JAR not found!"
    exit 1
fi

if [ ! -f "$D8_PATH" ]; then
    echo "Error: d8 tool not found at $D8_PATH"
    exit 1
fi

if [ ! -f "$ANDROID_JAR" ]; then
    echo "Error: Android API $MIN_API platform not found at $ANDROID_JAR"
    exit 1
fi

# Clean previous artifacts
rm -rf $TEMPDIR
mkdir -p $TEMPDIR

# Extract required resources from original JAR
echo "Extracting resources from $INPUT_JAR..."
cd $TEMPDIR
# unzip -q "../$INPUT_JAR" plugin.ini preferences.json locale/* -d "../$TEMPDIR" 2>/dev/null
$JAVA_PATH/bin/jar xf "../$INPUT_JAR" plugin.ini preferences.json locale
cd -

# Compile to DEX format
echo "Converting to Android bytecode (API $MIN_API)..."
"$D8_PATH" \
    --release \
    --min-api $MIN_API \
    --lib "$ANDROID_JAR" \
    --output $TEMPDIR \
    "$INPUT_JAR"

# Check DEX generation
if [ ! -f "tmp/classes.dex" ]; then
    echo "Error: DEX conversion failed!"
    exit 1
fi

# Create new Android-compatible JAR
echo "Building final Android JAR..."
(
    cd $TEMPDIR || exit 1
    $JAVA_PATH/bin/jar cf "../$OUTPUT_JAR" classes.dex
    $JAVA_PATH/bin/jar uf "../$OUTPUT_JAR" plugin.ini preferences.json locale 2>/dev/null
)

# Add original resources (excluding classes)
echo "Merging original resources..."
$JAVA_PATH/bin/jar uf "$OUTPUT_JAR" -C "$INPUT_JAR" . 2>/dev/null

# Cleanup
rm -rf $TEMPDIR

echo "Successfully built Android-compatible JAR: $OUTPUT_JAR"
```

**Comment by pramit-j2-sl** [comment]
I copy pasted generated .jar (androified) to the plugin folder (assets/plugins). I am still getting the errors:

```
2025-03-20 14:08:55.160   644-1710  AppOps                  system_server                        E  Bad call made by uid 10109. Package "io.github.krlvm.powertunnel.android.dev" does not belong to uid 10109.
2025-03-20 14:08:55.167   644-1710  AppOps                  system_server                        E  Cannot noteOperation
                                                                                                    java.lang.SecurityException: Specified package "io.github.krlvm.powertunnel.android.dev" under uid 10109 but it is not
                                                                                                    	at com.android.server.appop.AppOpsService.verifyAndGetBypass(AppOpsService.java:4668)
                                                                                                    	at com.android.server.appop.AppOpsService.verifyAndGetBypass(AppOpsService.java:4528)
                                                                                                    	at com.android.server.appop.AppOpsService.noteOperationUnchecked(AppOpsService.java:3129)
                                                                                                    	at com.android.server.appop.AppOpsService.noteOperationImpl(AppOpsService.java:3116)
                                                                                                    	at com.android.server.appop.AppOpsService.-$$Nest$mnoteOperationImpl(AppOpsService.java:0)
                                                                                                    	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher.$r8$lambda$9t8iLhni7XlJaYUbHyUsLY8CxCM(AppOpsService.java:0)
                                                                                                    	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher$$ExternalSyntheticLambda1.apply(R8$$SyntheticClass:0)
                                                                                                    	at com.android.server.policy.AppOpsPolicy.noteOperation(AppOpsPolicy.java:251)
                                                                                                    	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher.noteOperation(AppOpsService.java:7401)
                                                                                                    	at com.android.server.appop.AppOpsService.noteOperation(AppOpsService.java:3074)
                                                                                                    	at android.app.AppOpsManager.noteOpNoThrow(AppOpsManager.java:9062)
                                                                                                    	at android.app.AppOpsManager.noteOpNoThrow(AppOpsManager.java:9042)
                                                                                                    	at android.app.AppOpsManager.noteOpNoThrow(AppOpsManager.java:9019)
                                                                                                    	at com.android.server.connectivity.Vpn.doesPackageHaveAppop(Vpn.java:1395)
                                                                                                    	at com.android.server.connectivity.Vpn.isVpnServicePreConsented(Vpn.java:1400)
                                                                                                    	at com.android.server.connectivity.Vpn.isVpnPreConsented(Vpn.java:1379)
                                                                                                    	at com.android.server.connectivity.Vpn.prepare(Vpn.java:1229)
                                                                                                    	at com.android.server.VpnManagerService.prepareVpn(VpnManagerService.java:227)
                                                                                                    	at android.net.IVpnManager$Stub.onTransact(IVpnManager.java:316)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1500)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1444)
2025-03-20 14:08:55.662  7944-7958  EGL_emulation           io....krlvm.powertunnel.android.dev  D  app_time_stats: avg=33.30ms min=12.46ms max=132.18ms count=26
2025-03-20 14:08:56.674  7944-7958  EGL_emulation           io....krlvm.powertunnel.android.dev  D  app_time_stats: avg=22.20ms min=10.66ms max=37.26ms count=31
2025-03-20 14:08:57.679  7944-7958  EGL_emulation           io....krlvm.powertunnel.android.dev  D  app_time_stats: avg=21.14ms min=11.62ms max=44.81ms count=30
2025-03-20 14:08:58.287  7944-7944  nativeloader            io....krlvm.powertunnel.android.dev  D  Load /data/app/~~f1Ihht4gdM1mACQlFiZtnw==/io.github.krlvm.powertunnel.android.dev-e82vl-DDLk5IKIVJNxVyxg==/lib/x86_64/libtun2http.so using ns clns-7 from class loader (caller=/data/app/~~f1Ihht4gdM1mACQlFiZtnw==/io.github.krlvm.powertunnel.android.dev-e82vl-DDLk5IKIVJNxVyxg==/base.apk!classes8.dex): ok
2025-03-20 14:08:58.369  7944-8061  ProxyManager            io....krlvm.powertunnel.android.dev  D  Starting server...
2025-03-20 14:08:58.380  7944-8061  nel.android.dev         io....krlvm.powertunnel.android.dev  E  Attempt to load writable dex file: /data/user/0/io.github.krlvm.powertunnel.android.dev/files/plugins/Hosts-1.1-Androidified.jar
2025-03-20 14:08:58.381  7944-8061  ziparchive              io....krlvm.powertunnel.android.dev  W  Unable to open '/data/user/0/io.github.krlvm.powertunnel.android.dev/files/plugins/Hosts-1.1-Androidified.dm': No such file or directory
```

Any help/idea @krlvm ?

**Comment by pramit-j2-sl** [comment]
Not sure what I'm doing wrong, as I am very new to android/java dev:

```
#!/bin/bash

# Configuration
INPUT_JAR="powertunnel-plugin-template-1.0.jar"
OUTPUT_JAR="powertunnel-plugin-template-1.0-Androidified.jar"

ANDROID_SDK_PATH="/data/Android/Sdk"
BUILD_TOOLS_VERSION="35.0.1"
MIN_API=16
JAVA_PATH="/usr/local/android-studio/jbr"

DEFAULT_XMX="-Xmx1024M"
DEFAULT_XSS="-Xss1m"

# Path setup
# D8_PATH="$ANDROID_SDK_PATH/build-tools/$BUILD_TOOLS_VERSION/d8"
D8_JAR="$ANDROID_SDK_PATH/build-tools/$BUILD_TOOLS_VERSION/lib/d8.jar"
ANDROID_JAR="$ANDROID_SDK_PATH/platforms/android-$MIN_API/android.jar"

# Internal Filenames
TEMPDIR="./tmp"

# Java Options
JAVA_OPTS="$DEFAULT_XMX $DEFAULT_XSS"

# Clean previous artifacts
rm -rf $TEMPDIR
mkdir -p $TEMPDIR
rm $OUTPUT_JAR

$JAVA_PATH/bin/java $JAVA_OPTS -classpath "$D8_JAR:$ANDROID_JAR" -cp $D8_JAR com.android.tools.r8.D8 --min-api 16 --lib $ANDROID_JAR --output $OUTPUT_JAR $INPUT_JAR

cd $TEMPDIR
# unzip -q "../$INPUT_JAR" plugin.ini preferences.json locale/* -d "../$TEMPDIR" 2>/dev/null
$JAVA_PATH/bin/jar xf "../$INPUT_JAR" plugin.ini preferences.json locale
$JAVA_PATH/bin/jar uf "../$OUTPUT_JAR" ./plugin.ini ./preferences.json ./locale
cd -
```

This I am using to convert the generated jar (java bytecode) file.
