### ISSUE TITLE
PowerTunnel v2.6 ~ 2.6.3 Force Close on Redmi 4A

### ISSUE THREAD

**Issue by MicroBeast** [krlvm/PowerTunnel-Android#147]
PowerTunnel:
v2.6 ~ 2.6.3

Devices:
Redmi 4A, Android 7.1.2, arm64

Issues:
Set up DNS with any true DNS/DoH (including from dropdown menu) will force close PowerTunnel.

PowerTunnel v1.9.1 up to v2.5 doesn't crash.

**Comment by krlvm** [comment]
Please, provide logs - they can be extracted using built-in functionality or with ADB

**Comment by MicroBeast** [comment]
[powertunnel_after_fresh_start.log](https://github.com/krlvm/PowerTunnel-Android/files/11465247/powertunnel_after_fresh_start.log)
[powertunnel_after_force_close.log](https://github.com/krlvm/PowerTunnel-Android/files/11465248/powertunnel_after_force_close.log)

**Comment by krlvm** [comment]
Seems like a problem with firmware - the crash occurs during plugin loading - it is done with reflection:

```
W ReflectionUtils: 
W ReflectionUtils: java.lang.NoSuchMethodException: android.os.MessageQueue#enableMonitor()#bestmatch
W ReflectionUtils: 	at miui.util.ReflectionUtils.findMethodBestMatch(ReflectionUtils.java:338)
W ReflectionUtils: 	at miui.util.ReflectionUtils.findMethodBestMatch(ReflectionUtils.java:375)
W ReflectionUtils: 	at miui.util.ReflectionUtils.callMethod(ReflectionUtils.java:800)
W ReflectionUtils: 	at miui.util.ReflectionUtils.tryCallMethod(ReflectionUtils.java:818)
W ReflectionUtils: 	at android.os.BaseLooper.enableMonitor(BaseLooper.java:47)
W ReflectionUtils: 	at android.os.Looper.prepareMainLooper(Looper.java:112)
W ReflectionUtils: 	at android.app.ActivityThread.main(ActivityThread.java:6221)
W ReflectionUtils: 	at java.lang.reflect.Method.invoke(Native Method)
W ReflectionUtils: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
W ReflectionUtils: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

I works with MIUI on Android >= 9 at least though.

You can use [the latest stable version](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.9.1) released before plugin system introduction.

**Comment by MicroBeast** [comment]
Yes, I'm using v1.9.1 on that device. As I also mentioned on OP, the last version that is not instantly force closed is v2.5.

No hurry, I was just reporting. I just still run my old devices as long they still work.

Thanks.
