### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by ghost** [krlvm/PowerTunnel-Android#84]
App version - 2.0-rc3 / rc4
OS version - 11 (API 30)

java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = io.github.krlvm.powertunnel.preferences.PreferenceGroup)
	at android.os.Parcel.writeSerializable(Parcel.java:2113)
	at android.os.Parcel.writeValue(Parcel.java:1883)
	at android.os.Parcel.writeList(Parcel.java:1092)
	at android.os.Parcel.writeValue(Parcel.java:1832)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1627)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:125)
	at android.os.Parcel.writeTypedObject(Parcel.java:1737)
	at android.os.Parcel.writeTypedList(Parcel.java:1616)
	at android.os.Parcel.writeTypedList(Parcel.java:1573)
	at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:58)
	at android.os.Parcel.writeParcelable(Parcel.java:1904)
	at android.os.Parcel.writeValue(Parcel.java:1810)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1627)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1627)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1627)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4388)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.io.NotSerializableException: androidx.preference.EditTextPreference
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:762)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1036)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1552)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2108)
	... 36 more

**Comment by krlvm** [comment]
This crash is literally unexpected, how did you achieve it?
However, this build might fix it:
[PowerTunnel-99-hotfix.zip](https://github.com/krlvm/PowerTunnel-Android/files/7091981/PowerTunnel-99-hotfix.zip)

**Comment by krlvm** [comment]
This build should fix the issue: 
[PowerTunnel-99-hotfix.zip](https://github.com/krlvm/PowerTunnel-Android/files/7092081/PowerTunnel-99-hotfix.zip)

**Comment by user6660** [comment]
Can confirm there were no crashes on that build. Thanks.
