### ISSUE TITLE
Падает при переключении окна тач - кнопкой, когда открыта панель настроек LibertyTunnel

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#85]
Стабильно падает при переключении окна тач - кнопкой, когда открыта панель настроек LibertyTunnel

![2021 09 02_06 58 28~01](https://user-images.githubusercontent.com/12525093/131744485-9775794f-4216-4273-872d-b1bcbcc6a713.jpg)

А если потом вернуться, выйти в главное меню и перезапустить PT, получаю вот такое :

```java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = io.github.krlvm.powertunnel.preferences.PreferenceGroup)
	at android.os.Parcel.writeSerializable(Parcel.java:1394)
	at android.os.Parcel.writeValue(Parcel.java:1341)
	at android.os.Parcel.writeList(Parcel.java:717)
	at android.os.Parcel.writeValue(Parcel.java:1290)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
	at android.os.Bundle.writeToParcel(Bundle.java:1034)
	at android.os.Parcel.writeBundle(Parcel.java:669)
	at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:125)
	at android.os.Parcel.writeTypedList(Parcel.java:1112)
	at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:58)
	at android.os.Parcel.writeParcelable(Parcel.java:1363)
	at android.os.Parcel.writeValue(Parcel.java:1268)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
	at android.os.Bundle.writeToParcel(Bundle.java:1034)
	at android.os.Parcel.writeBundle(Parcel.java:669)
	at android.os.Parcel.writeValue(Parcel.java:1265)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
	at android.os.Bundle.writeToParcel(Bundle.java:1034)
	at android.os.Parcel.writeBundle(Parcel.java:669)
	at android.os.Parcel.writeValue(Parcel.java:1265)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
	at android.os.Bundle.writeToParcel(Bundle.java:1034)
	at android.os.Parcel.writeBundle(Parcel.java:669)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3016)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3553)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by: java.io.NotSerializableException: androidx.preference.EditTextPreference
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
	at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
	at java.util.ArrayList.writeObject(ArrayList.java:648)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1033)
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
	at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
	at android.os.Parcel.writeSerializable(Parcel.java:1389)
	... 36 more```

**Comment by krlvm** [comment]
Duplicate of #84 

Версия с исправлением: https://github.com/krlvm/PowerTunnel-Android/issues/84#issuecomment-910357012

**Comment by krlvm** [comment]
Duplicate of #84
