### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Dats1K** [krlvm/PowerTunnel-Android#87]
App version: 2.0 rc4 (99)
Core version: 2.0 rc5.(99)
Android 9
Error: unable to stop service io.github.krlvm.
java.lang.RuntimeException: Unable to stop service io.github.krlvm.powertunnel.android.services.TunnelingVpnService@77d0d71: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.resolveTypeIfNeeded(android.content.ContentResolver)' on a null object reference
	at android.app.ActivityThread.handleStopService(ActivityThread.java:3943)
	at android.app.ActivityThread.access$1800(ActivityThread.java:238)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7073)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.resolveTypeIfNeeded(android.content.ContentResolver)' on a null object reference
	at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1068)
	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:449)
	at io.github.krlvm.powertunnel.android.services.TunnelingVpnService.disconnect(TunnelingVpnService.java:224)
	at io.github.krlvm.powertunnel.android.services.TunnelingVpnService.disconnect(TunnelingVpnService.java:190)
	at io.github.krlvm.powertunnel.android.services.TunnelingVpnService.onDestroy(TunnelingVpnService.java:89)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:3923)
	... 8 more

**Comment by krlvm** [comment]
Thanks for reporting this, it is fixed in an upcoming release.
